# =========================================================================
# CLEANUP AND ORGANIZATION SCRIPT
# =========================================================================
# This script removes redundant files and organizes the remaining analysis files
# =========================================================================

cat("================================================================================\n")
cat("CLEANING UP AND ORGANIZING ANALYSIS FILES\n")
cat("================================================================================\n")

# Files to remove (redundant or superseded)
files_to_remove <- c(
  # Redundant VIF analysis (now consolidated)
  "scripts/advanced/vif_analysis_phasic_residualization.R",
  
  # Redundant timing multiverse scripts
  "scripts/advanced/timing_multiverse_alternative.R",
  "scripts/advanced/timing_multiverse_stacking_analysis.R",
  "scripts/advanced/timing_multiverse_stacking_analysis.R",
  
  # Redundant z-bias scripts
  "scripts/advanced/fit_hddm_z_bias_model.R",
  "scripts/advanced/fit_simple_hddm_z_bias.R",
  "scripts/advanced/fit_z_bias_hddm.R",
  "scripts/advanced/fit_z_bias_glmer.R",
  
  # Redundant robustness scripts
  "scripts/advanced/robustness_checks_analysis.R",
  
  # Redundant stacking analysis
  "scripts/advanced/stacking_analysis_timing_multiverse.R",
  
  # Redundant HDDM scripts
  "scripts/advanced/fit_robust_hddm_base_pupil.R",
  "scripts/advanced/fit_simple_hddm_base_pupil.R",
  
  # Redundant analysis scripts
  "scripts/advanced/analyze_z_bias_hypothesis.R",
  "scripts/advanced/between_person_analysis_individual_differences.R",
  "scripts/advanced/mediation_analysis_effort_pupillometry.R",
  "scripts/advanced/fit_hierarchical_ddm_pupillometry.R",
  "scripts/advanced/fit_hierarchical_ddm_sequential_dependencies.R",
  "scripts/advanced/fit_hierarchical_lba_pupillometry.R",
  
  # Redundant utility scripts
  "scripts/utilities/analyze_phasic_timing_sensitivity.R",
  "scripts/utilities/create_pupillometry_features.R",
  "scripts/utilities/create_publication_figures_and_manuscript.R",
  
  # Redundant core scripts
  "scripts/core/run_bap_analysis.R",
  "scripts/core/run_bap_analysis_with_logging.R",
  "scripts/core/run_complete_bap_pipeline.R",
  "scripts/core/run_extended_analysis.R",
  
  # Redundant utility scripts
  "scripts/utilities/analyze_pipeline_logs.R",
  "scripts/utilities/logging_system.R",
  "scripts/utilities/pipeline_status.R",
  
  # Redundant verification scripts
  "scripts/advanced/verify_lapse_mixture_models.R",
  "scripts/advanced/correct_lapse_mixture_interpretation.R"
)

# Remove files
removed_count <- 0
for (file in files_to_remove) {
  if (file.exists(file)) {
    file.remove(file)
    cat("Removed:", file, "\n")
    removed_count <- removed_count + 1
  }
}

cat("\nRemoved", removed_count, "redundant files\n")

# Create new organized structure
cat("\nCreating organized file structure...\n")

# Create main analysis directory
if (!dir.exists("scripts/main_analysis")) {
  dir.create("scripts/main_analysis", recursive = TRUE)
}

# Move consolidated scripts to main_analysis
consolidated_scripts <- c(
  "scripts/comprehensive_bap_ddm_workflow.R"
)

for (script in consolidated_scripts) {
  if (file.exists(script)) {
    new_path <- file.path("scripts/main_analysis", basename(script))
    file.copy(script, new_path)
    cat("Copied to main_analysis:", basename(script), "\n")
  }
}

# Create README for main_analysis
readme_content <- "# Main Analysis Scripts

This directory contains the consolidated analysis scripts for the BAP DDM project.

## Primary Analysis Script

### comprehensive_bap_ddm_workflow.R
**Main consolidated analysis script** that performs:
1. State/Trait Decomposition
2. VIF Analysis and Residualization  
3. Base Pupil HDDM Fitting
4. Z-Bias Analysis
5. Timing Multiverse Analysis
6. Robustness Checks
7. Comprehensive Visualizations

## Usage

Run the complete analysis workflow:
source('scripts/main_analysis/comprehensive_bap_ddm_workflow.R')

## Output

The script generates:
- Comprehensive analysis results in output/results/
- Visualizations in output/figures/
- Model objects in output/models/

## Dependencies

- data/analysis_ready/bap_clean_pupil.csv (generated by state_trait_decomposition.R)
- R packages: brms, lme4, dplyr, ggplot2, car, tidyr, bayesplot, patchwork

## Note

This script consolidates multiple individual analysis scripts into a single, comprehensive workflow for easier execution and maintenance.
"

writeLines(readme_content, "scripts/main_analysis/README.md")

# Create summary of remaining files
cat("\n================================================================================\n")
cat("FILE ORGANIZATION SUMMARY\n")
cat("================================================================================\n")

cat("📁 REMAINING ORGANIZED STRUCTURE:\n")
cat("\n🔧 Core Analysis Scripts:\n")
cat("- scripts/main_analysis/comprehensive_bap_ddm_workflow.R (MAIN SCRIPT)\n")
cat("- scripts/main_analysis/README.md\n")

cat("\n🛠️ Utility Scripts:\n")
cat("- scripts/utilities/state_trait_decomposition.R (Data preprocessing)\n")
cat("- scripts/utilities/consolidate_results.R (Results consolidation)\n")
cat("- scripts/utilities/create_llm_friendly_summary.R (LLM-friendly output)\n")
cat("- scripts/utilities/data_integration.R (Data integration)\n")
cat("- scripts/utilities/extract_model_results.R (Model extraction)\n")

cat("\n📊 Original Analysis Scripts:\n")
cat("- scripts/01_data_processing/01_process_and_qc.R\n")
cat("- scripts/02_statistical_analysis/02_ddm_analysis.R\n")

cat("\n📚 Legacy Scripts (preserved):\n")
cat("- scripts/legacy/ (contains original analysis scripts)\n")

cat("\n📋 Documentation:\n")
cat("- output/results/COMPREHENSIVE_BAP_DDM_ANALYSIS_REPORT.md (MAIN REPORT)\n")
cat("- output/results/consolidated/ (LLM-friendly consolidated results)\n")

cat("\n🎯 KEY RECOMMENDATIONS:\n")
cat("1. Use scripts/main_analysis/comprehensive_bap_ddm_workflow.R for all analyses\n")
cat("2. Refer to output/results/COMPREHENSIVE_BAP_DDM_ANALYSIS_REPORT.md for results\n")
cat("3. Check output/results/consolidated/ for LLM-friendly summaries\n")
cat("4. Legacy scripts preserved in scripts/legacy/ for reference\n")

cat("\n================================================================================\n")
cat("CLEANUP COMPLETE\n")
cat("================================================================================\n")
